### ISSUE TITLE
Support for rr:graphMap

### ISSUE THREAD

**Issue by rnavarropiris** [tomatophantastico/sparqlmap-core#3]
Using the given table

```
CREATE TABLE "Person" (
          "id" VARCHAR(200), 
          "nick" VARCHAR(200), 
          "knows" VARCHAR(200), 
          "sameAs" VARCHAR(200), 
          "deathDate" VARCHAR(200), 
          "context" VARCHAR(200)
         )
```

the following mapping is accepted (the application starts normally):

```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix simpsons: <http://thesimpsons.com/> .

<#TriplesMapPerson>
    rr:logicalTable [ rr:tableName "Person" ];
    rr:subjectMap [
        rr:template "http://thesimpsons.com/{id}";
        rr:class simpsons:Person;
    ].
```

but crashes with the following one

```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix simpsons: <http://thesimpsons.com/> .

<#TriplesMapPerson>
    rr:logicalTable [ rr:tableName "Person" ];
    rr:subjectMap [
        rr:template "http://thesimpsons.com/{id}";
        rr:class simpsons:Person;
        rr:graphMap [ rr:template "http://thesimpsons.com/Graph{context}" ];
    ].
```

The exception is as follows:

```
java.lang.NullPointerException: null
    at org.aksw.sparqlmap.core.db.DBAccess.getDataType(DBAccess.java:165) ~[bin/:na]
    at org.aksw.sparqlmap.core.mapper.compatibility.SimpleCompatibilityChecker.<init>(SimpleCompatibilityChecker.java:53) ~[bin/:na]
    at org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLModel.loadCompatibilityChecker(R2RMLModel.java:408) ~[bin/:na]
    at org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLModel.setup(R2RMLModel.java:107) ~[bin/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_80]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    ... 162 common frames omitted
```

**Comment by tomatophantastico** [comment]
confirmed, most likely this issue is caused by a R2RML loading error.
