### ISSUE TITLE
Column mapping check error using Postgre 9.5

### ISSUE THREAD

**Issue by rnavarropiris** [tomatophantastico/sparqlmap-core#4]
# Exception

```
Caused by: org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLValidationException: Column name in virtual table mismatching definition in term map.
    at org.aksw.sparqlmap.core.db.DBAccess.getColumnName(DBAccess.java:137) ~[bin/:na]
    at org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLModel.getRealColumnName(R2RMLModel.java:796) ~[bin/:na]
    at org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLModel.cleanTemplate(R2RMLModel.java:828) ~[bin/:na]
    at org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLModel$TermMapQueryResult.<init>(R2RMLModel.java:686) ~[bin/:na]
    at org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLModel.loadTripleMaps(R2RMLModel.java:525) ~[bin/:na]
    at org.aksw.sparqlmap.core.config.syntax.r2rml.R2RMLModel.setup(R2RMLModel.java:102) ~[bin/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_80]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    ... 162 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column "personId" does not exist
  Hint: Perhaps you meant to reference the column "GraffityArtist"."personid".
  Position: 8
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157) ~[postgresql-9.2-1002-jdbc4.jar:na]
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886) ~[postgresql-9.2-1002-jdbc4.jar:na]
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.2-1002-jdbc4.jar:na]
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555) ~[postgresql-9.2-1002-jdbc4.jar:na]
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403) ~[postgresql-9.2-1002-jdbc4.jar:na]
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283) ~[postgresql-9.2-1002-jdbc4.jar:na]
    at com.jolbox.bonecp.StatementHandle.executeQuery(StatementHandle.java:464) ~[bonecp-0.8.0.RELEASE.jar:na]
    at org.aksw.sparqlmap.core.db.DBAccess.getColumnName(DBAccess.java:129) ~[bin/:na]
```
# Environment

Postgre server version: 9.5 [Docker image](https://github.com/docker-library/postgres/blob/a82c28e1c407ef5ddfc2a6014dac87bcc4955a26/9.5/Dockerfile)
jdbc connection URL: jdbc:postgresql://localhost:5432/user?padCharsWithSpace=true&sessionVariables=sql_mode=ANSI_QUOTES&user=user&password=pass
Mapping:

```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix simpsons: <http://thesimpsons.com/> .

<#TriplesMapGraffityArtirst>
    rr:logicalTable [ rr:tableName "GraffityArtist" ];
    rr:subjectMap [
        rr:template "http://thesimpsons.com/{personId}";
        rr:class simpsons:GraffityArtist;
    ].
```

Database:

```
CREATE TABLE "GraffityArtist" (
 personId VARCHAR(200)
 );
INSERT INTO "GraffityArtist" (personId) VALUES ('Bart');
```

**Comment by rnavarropiris** [comment]
Solved, PostgreSQL converts camelCase names to lower case. To avoid this behaviour, this syntax did the trick:

```
CREATE TABLE "GraffityArtist" (
 "personId" VARCHAR(200)
 );
INSERT INTO "GraffityArtist" ("personId") VALUES ('Bart');
```

**Comment by tomatophantastico** [comment]
closed as this is PostgreSQL syntax related.
